# Generated by Django 3.2.9 on 2021-11-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_object', models.FileField(upload_to='data/files', verbose_name='File Object')),
            ],
        ),
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_object', models.FileField(upload_to='data/files', verbose_name='File Object')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('processed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.processedfile', verbose_name='processed_file')),
            ],
        ),
    ]
